arb-dir: lib/src/l10n/arb
template-arb-file: app_en.arb
output-dir: lib/src/l10n
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: untranslated.json
preferred-supported-locales: ["en"]
required-resource-attributes: true
nullable-getter: false
use-deferred-loading: true
